+ BitGenerator: create sequences
+ Generator: use those sequences to sample from different distributions

Since Numpy v1.17.0, the Generator van be intialized with a number of different BitGenerators

Random Numpy number routines: NEP 19

In [1]:
from numpy.random import default_rng # default_rng is a new instance of generator, 
                                     # which has better statistical properties legacy RandomState, 
                                     # such as random_sample, rand, randint
rng = default_rng()
vals = rng.standard_normal(10)

In [2]:
vals

array([-0.82056305, -2.4898683 ,  0.62495203,  0.79185817, -1.57989144,
        0.82792347,  0.2623867 , -0.58139083, -0.47502098, -0.85138979])

In [3]:
from numpy.random import Generator, PCG64
rng = Generator(PCG64(12345))
rng.standard_normal()

-1.4238250364546312

In [4]:
rng = default_rng(12345)
rng.standard_normal()

-1.4238250364546312

Examples

In [5]:
# random integers from low (inclusive) to high (exclusive)
rng.integers(0, 10, 4)

array([7, 3, 2, 7])

In [6]:
# random floats in [0, 1)
rng.random()

0.6762546707509746

In [7]:
# random sample from a give array
print(
    rng.choice([1, 2, 3], 1)
)
print(
    rng.choice([1, 2, 3], 3)
)
print(
    rng.choice([1, 2, 3], 3, replace=False)
)

[3]
[2 3 1]
[2 3 1]


In [8]:
# random bytes 
rng.bytes(8)

b'-\x9e\xa8:w\xbd9\xac'

In [9]:
rng.beta(1,1,10)

array([0.17833593, 0.72957711, 0.3197939 , 0.63584491, 0.58547838,
       0.37733095, 0.66775679, 0.5676277 , 0.98606722, 0.69002562])

In [10]:
rng.binomial(10, 0.3, 10)

array([1, 3, 2, 2, 3, 2, 2, 3, 3, 2])

In [11]:
rng.chisquare(2, 10)

array([0.17290206, 2.69742915, 1.50914335, 2.40108175, 0.30126929,
       2.70873286, 1.11104923, 0.31855413, 0.33836534, 2.34961109])

In [12]:
rng.exponential(1.0, 10)

array([0.29117591, 1.43149027, 0.58704392, 0.30897818, 4.46967924,
       0.100007  , 0.18071266, 0.82828908, 0.97308074, 1.04407401])

In [13]:
rng.normal() # standard normal 

-0.7016908087073603

In [14]:
rng.normal(5, 2, 4) # mu, sigma, size

array([1.40857365, 6.63665124, 3.8579342 , 5.00157105])

In [15]:
rng.normal(0, 1, (10,3))

array([[-1.06364272,  1.3017145 ,  0.74787294],
       [ 0.98087591, -0.11041869,  0.46791853],
       [ 0.89060715,  1.02300937,  0.31238339],
       [-0.06190469, -0.35947965, -0.74864398],
       [-0.96547891,  0.36003466, -0.24455253],
       [-1.99585661, -0.15524762,  1.06383087],
       [-0.27517157, -1.85333593, -0.12434193],
       [ 0.78497452,  0.2019986 , -0.42807444],
       [ 1.8482889 ,  1.89995289, -0.09842503],
       [ 0.81344544,  0.39249439,  0.7814429 ]])

In [16]:
rng.standard_normal((10,3))

array([[ 1.45327152,  0.82018605,  0.08770534],
       [-0.65350565, -0.81188688, -0.02553817],
       [ 1.15818454,  0.30052087,  0.05305665],
       [ 0.25727152,  0.03574286,  0.54723669],
       [-1.12296158, -1.97524767, -0.42515005],
       [-1.14907382,  1.61513805, -0.15847686],
       [-0.25287335, -1.53815403,  0.28208603],
       [-0.62361213,  1.12182226,  0.84122103],
       [-0.7758961 ,  0.41071644, -2.7224161 ],
       [-0.6733048 ,  1.24622153,  0.79020803]])